### ISSUE TITLE
hi there regarding the pathslider. 

### ISSUE THREAD

**Issue by gerble1000** [Mottie/Pathslider#1]
i have it curved exactly how i want it and its moving freely.
my question is how do i set the position using javascript and how would i use it the same way as i am using this volume control.

```html
<input type="range" id="volume"  width="500" height="20px" min="0" max="100" step="1"oninput="actions(this.id,this.value);" onchange="actions(this.id,this.value);"/>
```

i would like to use 2 sliders on the same page.
any chance you could give me an example on how to interact with the slider please. BTW i love it, very easy to implement :)

my email address is gerble1000@hotmail.com

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
