### ISSUE TITLE
Diffrent line collors

### ISSUE THREAD

**Issue by AviFix** [Mottie/Pathslider#2]
Hi
Thanks for your great work.

i was wondering if there is away to have different colors for the line (before and after the Grip)
![curved slider](https://cloud.githubusercontent.com/assets/3835504/5262905/c1ee855e-7a33-11e4-8537-a54eff05dca3.png)

Thank's allot

Avi

**Comment by Mottie** [comment]
You can now add a second color to the `curve.color` value to add a color to either side of the grip [demo](https://jsfiddle.net/Mottie/ZAtGE/49/):

``` js
curve: {
  width: 2,
  color: ["#f00", "#00f"],
  cap: "round"
}
```

For additional tweaks, a [`drawCanvas` callback](https://github.com/Mottie/Pathslider/wiki/Options#drawcanvas) was added. A code example can be seen in issue #8.
